version: "3.7"
services:
  app:
    build:
      args:
        user: waqf
        uid: 1000
      context: $PWD
      dockerfile: Dockerfile
    env_file:
      - back.env
    image: waqfapp
    container_name: app
    restart: always
    working_dir: /var/www/
    ports:
      - "${IP:-127.0.0.1}:9000:9000"
    volumes:
      - $PDW:/var/www

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - "${IP:-127.0.0.1}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
       - mysql:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD:/var/www
      - $PWD/docker-compose/nginx:/etc/nginx/conf.d

volumes:
  - mysql: {}
