version: "3.7"
services:
  app:
    build:
      args:
        user: waqf
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: waqfapp
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - travellist

  websocket:
    build:
      args:
        user: waqf
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: waqfapp-websocket
    entrypoint: /entrypoint-websocket
    command: php artisan websockets:serve
    container_name: websocket
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - "6001:6001"
    networks:
      - travellist

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
       - mysql:/var/lib/mysql
    networks:
      - travellist

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/app_conf.local:/etc/nginx/conf.d/default.conf
    networks:
      - travellist


  adminer:
    image: adminer
    restart: always

networks:
  travellist:
    driver: bridge

volumes:
  mysql:
