#!/bin/sh
set -e


# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi
echo composer install
composer install
echo php artisan key:generate
php artisan key:generate
echo php artisan migrate
php artisan migrate
echo php artisan migrate:refresh --seed
php artisan migrate:refresh --seed
echo php artisan storage:link
php artisan storage:link

exec "$@"
