#!/bin/sh
set -e

while ! nc -z app 9000; do
  sleep 1
done

>&2 echo "App is up - executing command"

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"
